### ISSUE TITLE
issue with krakenuniq output when running on KrakenUniq full NCBI NT database

### ISSUE THREAD

**Issue by CjeicaM** [NBISweden/aMeta#136] opened 2023-09-27 17:09 UTC
The krakenuniq.output file contains a newline CR character inserted in each line after the rank column, therefore the pipeline fails after that step. This does not happen with the microbial version of the database.
The workflow was run on our HPC cluster (Rocky Linux environment with slurm), two different installations of krakenuiq (1.0.0 and 1.0.4) were tested.

**Comment by clami66** [comment] 2023-10-03 12:01
Hi @CjeicaM that's an interesting issue, thanks for being in touch about it.

From the logs that @LeandroRitter showed me:
```
Error in rule KrakenUniq_AbundanceMatrix:
    jobid: 15
    input: results/KRAKENUNIQ/RS105.RISE505.MA873_L1_S2.trim/krakenuniq.output.filtered
```

Looks like the issue is directly caused by the `results/KRAKENUNIQ/RS105.RISE505.MA873_L1_S2.trim/krakenuniq.output.filtered` file. Could you attach this file from a run that failed? 

Thanks

**Comment by CjeicaM** [comment] 2023-10-10 16:54
Hi, sorry for the delay. 
I am attaching both the results/KRAKENUNIQ/RS105.RISE505.MA873_L1_S2.trim/krakenuniq.output.filtered file and results/KRAKENUNIQ/RS105.RISE505.MA873_L1_S2.trim/krakenuniq.output file. I think the fact that the filtered file is erroneous is due to the occurrence of the carriage return characters in krakenuniq.output file.
[krakenuniq.output.txt](https://github.com/NBISweden/aMeta/files/12859790/krakenuniq.output.txt)
[krakenuniq.output.filtered.txt](https://github.com/NBISweden/aMeta/files/12859800/krakenuniq.output.filtered.txt)

**Comment by NikolayOskolkov** [comment] 2023-10-19 12:27
@CjeicaM did you by any chance use Mobaexterm when you discovered the CR inserted to the KrakenUniq report file (or when running aMeta at HPC)?

**Comment by clami66** [comment] 2023-11-09 08:09
@CjeicaM could you do as described in issue #137 , specifically by replacing the taxDB file in your full NT database as described [here](https://github.com/NBISweden/aMeta/issues/137#issuecomment-1786805440) ?

**Comment by CjeicaM** [comment] 2023-11-09 16:45
Hi,

I try doing it in the next couple of days, and I'll let you know about the
results.

Maciej

czw., 9 lis 2023 o 09:09 Claudio Mirabello ***@***.***>
napisał(a):

**Comment by CjeicaM** [comment] 2023-11-11 10:25
Hi, This seemed to resolve the issue. The pipeline is still running but its already past the krakenuniq step, it did not report any error, and both krakenuniq.output and krakenuniq.output.filtered look fine (run through MobaXterm on Windows machine, using screen and srun on Linux-based HPC).

**Comment by LeandroRitter** [comment] 2024-06-28 17:37
@clami66 the issue is back, one user who recently downloaded the database reported the ^M symbol in the krakenuniq.output. Did you upload the corrected taxDB to scilifelab figshare?

**Comment by clami66** [comment] 2024-07-09 14:28
Turns out, the new DB link was not pointing to the updated `taxdb` file. This should be fixed now

**Closed by clami66** 2024-07-09 14:28 UTC
